@startuml name 

hide circle

package "Presentation Layer" as Presentation {
    hide members
    class PartidaRestController
    class RondaRestController
    class ManoRestController
    class BazaRestController
    class TrucoRestController
    class CartaRestController
    class JugadorRestController
    class UserRestController
}

package "Business Logic Layer" as BusinessLogic {
    hide members
    class PartidaService
    class RondaService
    class ManoService
    class BazaService
    class TrucoService
    class CartaService
    class JugadorService
    class UserService
}

package "Resources Layer" as Resources {
    hide attributes
    interface PartidaRepository
    interface RondaRepository
    interface ManoRepository
    interface BazaRepository
    interface TrucoRepository
    interface CartaRepository
    interface JugadorRepository
    interface UserRepository
}

PartidaRestController ..> PartidaService
PartidaRestController ..> JugadorService

RondaRestController ..> RondaService

ManoRestController ..> ManoService
ManoRestController ..> TrucoService

BazaRestController ..> BazaService
BazaRestController ..> TrucoService

TrucoRestController ..> TrucoService

CartaRestController ..> CartaService

JugadorRestController ..> JugadorService

UserRestController ..> UserService
UserRestController ..> AuthoritiesService

PartidaService ..> PartidaRepository
PartidaService ..> RondaService
PartidaService ..> JugadorService
PartidaService ..> UserService

RondaService ..> RondaRepository
RondaService ..> PartidaService
RondaService ..> ManoService
RondaService ..> BazaService
RondaService ..> JugadorService

ManoService ..> ManoRepository
ManoService ..> CartaService
ManoService ..> JugadorService

BazaService ..> BazaRepository
BazaService ..> TrucoRepository
BazaService ..> PartidaService
BazaService ..> JugadorService

TrucoService ..> TrucoRepository
TrucoService ..> BazaRepository
TrucoService ..> ManoRepository
TrucoService ..> JugadorService
TrucoService ..> ManoService
TrucoService ..> PartidaService
TrucoService ..> RondaService

CartaService ..> CartaRepository

JugadorService ..> JugadorRepository
JugadorService ..> PartidaRepository
JugadorService ..> UserRepository

UserService ..> UserRepository

@enduml
